=begin
#Tango Card RaaS API

#<p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2-SNAPSHOT

=end

require 'date'

module TangocardRaas
  class BrandRequirements
    # Always Show Disclaimer
    attr_accessor :always_show_disclaimer

    # Disclaimer Instructions
    attr_accessor :disclaimer_instructions

    # Display Instructions
    attr_accessor :display_instructions

    # Terms and Conditions Instructions
    attr_accessor :terms_and_conditions_instructions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'always_show_disclaimer' => :'alwaysShowDisclaimer',
        :'disclaimer_instructions' => :'disclaimerInstructions',
        :'display_instructions' => :'displayInstructions',
        :'terms_and_conditions_instructions' => :'termsAndConditionsInstructions'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'always_show_disclaimer' => :'Boolean',
        :'disclaimer_instructions' => :'String',
        :'display_instructions' => :'String',
        :'terms_and_conditions_instructions' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TangocardRaas::BrandRequirements` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TangocardRaas::BrandRequirements`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'always_show_disclaimer')
        self.always_show_disclaimer = attributes[:'always_show_disclaimer']
      end

      if attributes.key?(:'disclaimer_instructions')
        self.disclaimer_instructions = attributes[:'disclaimer_instructions']
      end

      if attributes.key?(:'display_instructions')
        self.display_instructions = attributes[:'display_instructions']
      end

      if attributes.key?(:'terms_and_conditions_instructions')
        self.terms_and_conditions_instructions = attributes[:'terms_and_conditions_instructions']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @always_show_disclaimer.nil?
        invalid_properties.push('invalid value for "always_show_disclaimer", always_show_disclaimer cannot be nil.')
      end

      if @disclaimer_instructions.nil?
        invalid_properties.push('invalid value for "disclaimer_instructions", disclaimer_instructions cannot be nil.')
      end

      if @display_instructions.nil?
        invalid_properties.push('invalid value for "display_instructions", display_instructions cannot be nil.')
      end

      if @terms_and_conditions_instructions.nil?
        invalid_properties.push('invalid value for "terms_and_conditions_instructions", terms_and_conditions_instructions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @always_show_disclaimer.nil?
      return false if @disclaimer_instructions.nil?
      return false if @display_instructions.nil?
      return false if @terms_and_conditions_instructions.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          always_show_disclaimer == o.always_show_disclaimer &&
          disclaimer_instructions == o.disclaimer_instructions &&
          display_instructions == o.display_instructions &&
          terms_and_conditions_instructions == o.terms_and_conditions_instructions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [always_show_disclaimer, disclaimer_instructions, display_instructions, terms_and_conditions_instructions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        TangocardRaas.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
