=begin
#Tango Card RaaS API

#<p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for TangocardRaas::CatalogsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CatalogsApi' do
  before do
    # run before each test
    @api_instance = TangocardRaas::CatalogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CatalogsApi' do
    it 'should create an instance of CatalogsApi' do
      expect(@api_instance).to be_instance_of(TangocardRaas::CatalogsApi)
    end
  end

  # unit tests for get_catalog
  # Get all items in the Platform&#39;s Catalog.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :verbose Verbose payload
  # @return [CatalogViewVerbose]
  describe 'get_catalog test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
