=begin
#Tango Card RaaS API

#<p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for TangocardRaas::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @api_instance = TangocardRaas::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@api_instance).to be_instance_of(TangocardRaas::CustomersApi)
    end
  end

  # unit tests for create_customer
  # Create a new Customer on this Platform.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCustomerCriteria] :form &lt;strong&gt;displayName&lt;/strong&gt; - a friendly name for this customer &lt;br /&gt;&lt;br /&gt;&lt;strong&gt;customerIdentifier&lt;/strong&gt; - an official identifier for this customer. This identifier needs to be lowercase if alphabetic characters are used.
  # @return [CustomerViewNew]
  describe 'create_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_customer_account
  # Create an Account under a specific Customer on this Platform.
  # @param customer_identifier The customerIdentifier for the Customer under which you are creating a new account
  # @param [Hash] opts the optional parameters
  # @option opts [CreateAccountCriteria] :account_criteria &lt;strong&gt;contactEmail&lt;/strong&gt; - An email address for a designated representative for this account.&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;displayName&lt;/strong&gt; - A friendly name for this account&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;identifier&lt;/strong&gt; - A unique identifier for this account. This identifier must be lowercase if alphabetic characters are used.
  # @return [AccountView]
  describe 'create_customer_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer
  # Get details for a specific Customer on this Platform.
  # @param customer_identifier customerIdentifier
  # @param [Hash] opts the optional parameters
  # @return [CustomerViewSummary]
  describe 'get_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_customer_accounts1
  # Get a list of all Accounts created for a specific Customer on this Platform.
  # @param customer_identifier customerIdentifier
  # @param [Hash] opts the optional parameters
  # @return [AccountViewSummary]
  describe 'list_customer_accounts1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_customers
  # Get a list of all Customers on this Platform.
  # @param [Hash] opts the optional parameters
  # @return [CustomerViewSummary]
  describe 'list_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
